# Generated by Django 6.1 on 2026-09-02 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRaciMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('R', 'Responsible (Исполнитель)'), ('A', 'Accountable (Утверждающий)'), ('C', 'Consulted (Консультант)'), ('I', 'Informed (Информируемый)')], max_length=1, verbose_name='Роль RACI')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Примечание / Обязанности')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raci_assignments', to='tasks.task', verbose_name='Задача')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raci_roles', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Назначение RACI',
                'verbose_name_plural': 'Матрица RACI',
                'unique_together': {('task', 'user', 'role')},
            },
        ),
    ]
