# Generated by Django 6.1 on 2026-09-02 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_options_project_end_date_and_more'),
        ('tasks', '0002_taskracimatrix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название вехи')),
                ('description', models.TextField(blank=True, verbose_name='Критерии приемки вехи')),
                ('due_date', models.DateTimeField(verbose_name='Срок контрольной точки')),
                ('status', models.CharField(choices=[('planned', 'Запланирован'), ('achieved', 'Достигнут'), ('missed', 'Просрочен')], default='planned', max_length=20, verbose_name='Статус')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Контрольная точка (Milestone)',
                'verbose_name_plural': 'Контрольные точки (Milestones)',
                'ordering': ['due_date'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.milestone', verbose_name='Контрольная точка (Milestone)'),
        ),
    ]
