# Generated by Django 6.0.8 on 2026-09-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='module_settings',
            field=models.JSONField(blank=True, default=dict, help_text="Настройки видимости модулей: {'kanban': true, 'raci': true, 'milestones': true, 'risks': true}"),
        ),
    ]
