# Generated by Django 6.1 on 2026-09-02 13:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_alter_project_options_project_end_date_and_more'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование риска')),
                ('description', models.TextField(verbose_name='Описание и триггеры риска')),
                ('probability', models.PositiveSmallIntegerField(default=3, help_text='1 - Очень низкая, 5 - Почти неизбежно', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Вероятность (1-5)')),
                ('impact', models.PositiveSmallIntegerField(default=3, help_text='1 - Минимальное, 5 - Катастрофическое', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Влияние (1-5)')),
                ('score', models.PositiveSmallIntegerField(editable=False, verbose_name='Оценка риска (P x I)')),
                ('strategy', models.CharField(choices=[('avoid', 'Уклонение (Avoid)'), ('mitigate', 'Снижение (Mitigate)'), ('transfer', 'Передача (Transfer)'), ('accept', 'Принятие (Accept)')], default='mitigate', max_length=20, verbose_name='Стратегия реагирования')),
                ('response_plan', models.TextField(blank=True, verbose_name='План реагирования / Контрмеры')),
                ('status', models.CharField(choices=[('identified', 'Идентифицирован'), ('analyzed', 'Проанализирован'), ('action_required', 'Требует мер'), ('mitigated', 'Минимизирован'), ('occurred', 'Наступил (Инцидент)'), ('closed', 'Закрыт')], default='identified', max_length=20, verbose_name='Статус риска')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата выявления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_risks', to=settings.AUTH_USER_MODEL, verbose_name='Владелец риска')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='projects.project', verbose_name='Проект')),
                ('related_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_risks', to='tasks.task', verbose_name='Связанная задача')),
            ],
            options={
                'verbose_name': 'Риск',
                'verbose_name_plural': 'Реестр рисков',
                'ordering': ['-score', '-impact'],
            },
        ),
    ]
